### ISSUE TITLE
Thoughts on Path Env/Value Contention

### ISSUE THREAD

**Issue by metaskills** [rails-lambda/crypteia#18]
Thanks to @cameronlynn for pointing this out. It is possible to use two paths where a value like `SECRET` would be in both.

```yaml
X_CRYPTEIA_SSM1: x-crypteia-ssm-path:/myapp/1/env
X_CRYPTEIA_SSM2: x-crypteia-ssm-path:/myapp/2/env
SECRET: x-crypteia
```

In this case, there is no deterministic behavior on what the value of `SECRET` would be. Should we handle this? Document it? Etc?
